config/routes.rb
Rails.application.routes.draw do
  get 'metrics/index'
  get '/', to: redirect('landing.html')
  resources :users, only: [:index, :show], path: '/player'
  namespace :trail do
    resources :trail_scoreboards, only: [:index, :show], path: '/ranking'
    resources :user_to_trails, only: [:index, :show], path: '/' do
      member do
        get 'play', action: :play
        get 'resolution/:answer_id', action: :resolution
        resources :answers, only: [:create]
      end
    end
  end

  resources :metrics, only: [:index]

  namespace :match do
    resources :challenge_scoreboards, only: :index, path: '/ranking'
    resources :matches, path: '/' do
      member do
        put 'join'
        get 'question'
        get 'report', action: :show, controller: 'reports'
        resources :answers, only: [:create]
      end
    end
  end
  mount ActionCable.server => '/cable'

  resources :questions
  resources :matches do
    member do
      get 'question'
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :alternatives
  has_many :match_questions
  has_many :matches, through: :match_questions
  scope :random_questions, -> (limit) { limit(limit).order('RANDOM()')}
  scope :by_level, -> (level) { where(level: level) }
  belongs_to :trail
  enum level: { Baby: 0, Teen: 1, Master: 2}
  accepts_nested_attributes_for :alternatives
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: %i[ show edit update destroy ]

  # GET /questions or /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions or /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:title, :body, :correct_answer, :trail_id)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :correct_answer %>
    <%= form.select(:correct_answer, Question.correct_answers.keys.map {|key| [key.humanize, key]}) %>
  </div>

  <div class="field">
    <%= form.label :trail %>
    <%= form.select(:trail_id, options_from_collection_for_select(Trail.all.map, :id, :name)) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/_resolution.html.erb
<div>  
  <p>
    <%= question.resolution %><br>
    <strong>Resposta correta: <%= Alternative.letters.key(question.correct_answer) %></strong>
  </p>
</div>

app/views/questions/_show.html.erb
<div>  
  <div class="row">
    <div class="col">
      <strong id="notebook"><%= question.from %></strong>
      <br />
      <strong> TEMPO RESTANTE: <span id="timer"></span></strong>
    </div>
  </div>
  <p>
    <%= question.body %><br>
    <% if !question.image.nil? %>
      <figure>
        <%= image_tag question&.image %>
        <figcaption><%= question.title %></figcaption>
      </figure>
    <% else %>
      <strong><%= question.title %></strong>
    <% end %>
  </p>
</div>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Correct answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.title %></td>
        <td><%= question.body %></td>
        <td><%= question.correct_answer %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<div>
  <div id="timer"></div>
  <p>
    <%= @question.title %>
  </p>
  <p>
    <%= @question.body %>
  </p>
</div>