config/routes.rb
Rails.application.routes.draw do
  get 'metrics/index'
  get '/', to: redirect('landing.html')
  resources :users, only: [:index, :show], path: '/player'
  namespace :trail do
    resources :trail_scoreboards, only: [:index, :show], path: '/ranking'
    resources :user_to_trails, only: [:index, :show], path: '/' do
      member do
        get 'play', action: :play
        get 'resolution/:answer_id', action: :resolution
        resources :answers, only: [:create]
      end
    end
  end

  resources :metrics, only: [:index]

  namespace :match do
    resources :challenge_scoreboards, only: :index, path: '/ranking'
    resources :matches, path: '/' do
      member do
        put 'join'
        get 'question'
        get 'report', action: :show, controller: 'reports'
        resources :answers, only: [:create]
      end
    end
  end
  mount ActionCable.server => '/cable'

  resources :questions
  resources :matches do
    member do
      get 'question'
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :match, optional: true
  belongs_to :question
  belongs_to :user_to_trail, optional: true
  belongs_to :alternative, optional: true
  before_create :check_correct

  after_create :update_match, if: :is_match?
  after_create :update_user_trail, if: :is_trail?

  scope :by_user, -> (user) { where(user: user) }
  scope :in_match, -> (match) { where(match: match) }
  scope :correct_answers, -> { where(correct: true) }
  scope :wrong_answers, -> { where(correct: false) }
  scope :with_questions, -> { joins(:question) }
  scope :valid, -> { where(timedout: false) }
  scope :from_matches, -> { where("match_id is not null")}
  scope :from_trail, -> { where("user_to_trail_id is not null")}

  def check_correct
    self.correct = self.alternative.correct
  end

  def self.calculate_correct(user, match)
    self.correct_answers.by_user(user).in_match(match).valid.count
  end

  private

  def update_match
    self.match.update_player_question(self.user)
  end

  def update_user_trail
    if self.correct
      self.user_to_trail.add_correct
    else
      self.user_to_trail.add_wrong
    end
  end

  def is_match?
    !self.match_id.nil?
  end

  def is_trail?
    !self.user_to_trail_id.nil?
  end

  def warn
    ActionCable.server.broadcast("Match-#{self.match_id}", "test")
  end
end

app/controllers/match/answers_controller.rb
class Match::AnswersController < ApplicationController
  before_action :set_answer, only: %i[ show ]
  before_action :validate_user, only: %i[ create ]
  after_action :set_match_status, only: %i[ create ]

  def index
    @answers = Answer.all
  end

  def show
  end

  def new
    @answer = Answer.new
  end

  def create
    @answer = Answer.new(answer_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @answer.save!
        format.html { redirect_to controller: "matches", action: "question", id: @answer.match.id }
        format.json { render :show, status: :created, location: @answer }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  private
  def set_answer
    @answer = Answer.find(params[:id])
  end

  def set_match_status
    match = Match.find(answer_params[:match_id])
    match.update_match_status
  end

  def answer_params
    params.require(:answer).permit(:value, :match_id, :alternative_id, :question_id, :timedout)
  end

  def validate_user
    match = Match.find(answer_params[:match_id])
    unless current_user == match.player1 || current_user == match.player2
      flash[:error] = "Falha ao responder pergunta, você não está vinculado a essa partida"
    end
  end
end

app/controllers/trail/answers_controller.rb
class Trail::AnswersController < ApplicationController
  before_action :set_answer, only: %i[ show ]
  before_action :validate_user, only: %i[ create ]

  def index
    @answers = Answer.all
  end

  def show
  end

  def new
    @answer = Answer.new
  end

  def create
    level = UserToTrail.find(answer_params[:user_to_trail_id]).level
    @answer = Answer.new(answer_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @answer.save!
        new_level = UserToTrail.find(answer_params[:user_to_trail_id]).level
        flash[:notice] = "Parabéns!!!! Você passou de nível!!!" if level != new_level
        format.html { redirect_to controller: "user_to_trails", action: "resolution", id: @answer.user_to_trail.id, answer_id: @answer.id }
        format.json { render :show, status: :created, location: @answer }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:value, :alternative_id, :question_id, :timedout, :user_to_trail_id)
  end

  def validate_user
    trail = UserToTrail.find(params[:id])
    unless current_user == trail.user
      flash[:error] = "Falha ao responder pergunta, você não está vinculado a essa trilha"
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: answer, class: "answer_form", url: url_opts) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
        <% answer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :timedout, value: false %>
  <div class="form-check">
    <%= form.collection_radio_buttons :alternative_id, question.alternatives, :id, :text, html_options: { class: 'form-control', required: true } do |b|%>
      <% if !b.object.image.nil? %>
        <%= b.label(class: "form-check-label") { b.radio_button(class: "form-check-input" ) + "#{b.object.letter}) " + image_tag(b.object.image) } %> <br />
      <% else %>
        <%= b.label(class: "form-check-label") { b.radio_button(class: "form-check-input" ) + "#{b.object.letter}) " + b.text } %> <br />
      <% end %>
    <% end %>
  </div>
  <% if !local_variables.include?(:view_only) || !view_only %>
    <%= form.hidden_field :match_id %>
    <%= form.hidden_field :user_to_trail_id %>
    <%= form.hidden_field :question_id %>
    <br />

    <div class="actions">
      <%= form.submit("Responder", { id: "answer_submit", class: "btn btn-primary" }) %>
    </div>
  <% end %>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>Correct</th>
      <th>User</th>
      <th>Match</th>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.choice %></td>
        <td><%= answer.correct %></td>
        <td><%= answer.user_id %></td>
        <td><%= answer.match_id %></td>
        <td><%= answer.question_id %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p>
  <strong>Value:</strong>
  <%= @answer.choice %>
</p>

<p>
  <strong>Correct:</strong>
  <%= @answer.correct %>
</p>

<p>
  <strong>User:</strong>
  <%= @answer.user_id %>
</p>

<p>
  <strong>Match:</strong>
  <%= @answer.match_id %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>