config/routes.rb
Rails.application.routes.draw do
  get 'metrics/index'
  get '/', to: redirect('landing.html')
  resources :users, only: [:index, :show], path: '/player'
  namespace :trail do
    resources :trail_scoreboards, only: [:index, :show], path: '/ranking'
    resources :user_to_trails, only: [:index, :show], path: '/' do
      member do
        get 'play', action: :play
        get 'resolution/:answer_id', action: :resolution
        resources :answers, only: [:create]
      end
    end
  end

  resources :metrics, only: [:index]

  namespace :match do
    resources :challenge_scoreboards, only: :index, path: '/ranking'
    resources :matches, path: '/' do
      member do
        put 'join'
        get 'question'
        get 'report', action: :show, controller: 'reports'
        resources :answers, only: [:create]
      end
    end
  end
  mount ActionCable.server => '/cable'

  resources :questions
  resources :matches do
    member do
      get 'question'
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :player1, class_name: 'User'
  belongs_to :player2, class_name: 'User', optional: true
  belongs_to :winner, class_name: 'User', optional: true
  belongs_to :loser, class_name: 'User', optional: true
  has_many :match_questions
  has_many :questions, through: :match_questions
  before_create :set_match_info
  before_create :set_match_questions

  enum status: { awaiting: 0, ongoing: 1, finished: 2 }

  enum player1_status: { started: 0, done: 1}, _prefix: true
  enum player2_status: { started: 0, done: 1}, _prefix: true
  
  scope :with_questions, -> { joins(:questions) }

  def get_question(current_user)
    if current_user == self.player1
      self.questions.order(:id)[self.player1_current_question]
    else
      self.questions.order(:id)[self.player2_current_question]
    end
  end

  def update_player_question(current_user)
    num_questions = self.questions.length - 1
    if current_user == self.player1 && self.player1_status_started?
      if self.player1_current_question >= num_questions
        self.player1_status = :done
        self.save
        return
      end
      self.player1_current_question += 1
    elsif current_user == self.player2 && self.player2_status_started?
      if self.player2_current_question >= num_questions
        self.player2_status = :done
        self.save
        return
      end
      self.player2_current_question += 1
    end
    self.save
  end

  def update_match_status
    if self.player1_status_done? && self.player2_status_done?
      self.status = :finished
      self.calculate_winner
    end
  end
  private

  def set_match_info
    self.status = :awaiting
    self.player1_current_question = 0
    self.player2_current_question = 0
  end

  def set_match_questions
    self.questions = Question.random_questions(5)
  end

  def calculate_winner
    correct_by_player1 = Answer.calculate_correct(self.player1, self.id)
    correct_by_player2 = Answer.calculate_correct(self.player2, self.id)
    winner = correct_by_player1 > correct_by_player2 ? self.player1 : self.player2
    self.winner = winner
    self.loser = self.player1 == self.winner ? self.player2 : self.player1
    self.status = :finished
    self.update_scoreboard
    self.save
  end

  def update_scoreboard
    current_position = ChallengeScoreboard.get_position(self.winner.id)
    self.winner.challenge_scoreboard.add_win
    self.loser.challenge_scoreboard.add_loss
    new_position = ChallengeScoreboard.get_position(self.winner.id)
    self.update_badges(current_position, new_position)
  end

  def update_badges(current_position, new_position)
    if (new_position < current_position && new_position < 3)
      UserToBadge.create(user_id: self.winner.id, badge_id: new_position)
    end
  end
end

app/controllers/match/answers_controller.rb
class Match::AnswersController < ApplicationController
  before_action :set_answer, only: %i[ show ]
  before_action :validate_user, only: %i[ create ]
  after_action :set_match_status, only: %i[ create ]

  def index
    @answers = Answer.all
  end

  def show
  end

  def new
    @answer = Answer.new
  end

  def create
    @answer = Answer.new(answer_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @answer.save!
        format.html { redirect_to controller: "matches", action: "question", id: @answer.match.id }
        format.json { render :show, status: :created, location: @answer }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  private
  def set_answer
    @answer = Answer.find(params[:id])
  end

  def set_match_status
    match = Match.find(answer_params[:match_id])
    match.update_match_status
  end

  def answer_params
    params.require(:answer).permit(:value, :match_id, :alternative_id, :question_id, :timedout)
  end

  def validate_user
    match = Match.find(answer_params[:match_id])
    unless current_user == match.player1 || current_user == match.player2
      flash[:error] = "Falha ao responder pergunta, você não está vinculado a essa partida"
    end
  end
end

app/controllers/match/challenge_scoreboards_controller.rb
class Match::ChallengeScoreboardsController < ApplicationController
  before_action :set_challenge_scoreboard, only: %i[ show ]

  def index
    @rank_slice = ChallengeScoreboard.all
  end

  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge_scoreboard
      @challenge_scoreboard = ChallengeScoreboard.rank_slice(0)
    end

    # Only allow a list of trusted parameters through.
    def challenge_scoreboard_params
      params.require(:challenge_scoreboard).permit(:user_id, :wins, :losses, :points)
    end
end

app/controllers/match/matches_controller.rb
class Match::MatchesController < ApplicationController
  before_action :set_match, only: %i[ show edit join destroy question ]
  before_action :can_play, only: %i[ create join ]
  # GET /matches or /matches.json
  def index
    @matches = Match.where('player1_id = ? or player2_id = ?', current_user.id, current_user.id)
  end

  # GET /matches/1 or /matches/1.json
  def show
    redirect_to report_match_match_path(@match) if @match.finished?
    @player1_answer_count = Answer.correct_answers.by_user(@match.player1).in_match(@match).valid.count if !@match.player1.nil?
    @player2_answer_count = Answer.correct_answers.by_user(@match.player2).in_match(@match).valid.count if !@match.player2.nil?
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches or /matches.json
  def create
    @match = Match.new(match_params.merge(player1: current_user))

    respond_to do |format|
      if @match.save!
        format.html { redirect_to match_match_path(@match), notice: "Partida criada com sucesso. Envie este link para o usuário que deseja desafiar http://localhost:3000#{match_match_path(@match)}" }
        format.json { render :show, status: :created, location: @match }
      else
        flash[:notice] = "Pontuação insuficiente para iniciar uma partida"
        format.html { render :index, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1 or /matches/1.json
  def join
    respond_to do |format|
      if @match.update(player2: current_user, status: :ongoing)
        format.html { redirect_to match_match_path(@match), notice: "Você entrou na partida." }
        format.json { render :show, status: :ok, location: @match }
        warn_join({
          type: "player_join",
          message: "O jogador #{@match.player2.name} entrou na partida",
          player: @match.player2.name
        })
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  def question
    redirect_to match_match_path(@match.id) if @match.player1 == current_user && @match.player1_status_done?
    redirect_to match_match_path(@match.id) if @match.player2 == current_user && @match.player2_status_done?

    @question = @match.get_question(current_user)
  end

  # DELETE /matches/1 or /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: "Partida criada com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def match_params
      params.permit()
    end

    def warn_join(message)
      ActionCable.server.broadcast("Match-#{@match.id}", message)
    end

    def can_play
      unless current_user.can_play?
        puts "Foi aqui???"
        flash[:error] = "Devido a sua pontuação, você não está habilitado a entrar em partidas PVP!"
        redirect_to match_matches_path
      end
    end
end

app/controllers/match/reports_controller.rb
class Match::ReportsController < ApplicationController
  before_action :set_match, only: %i[ show ]
  before_action :set_match_answers, only: %i[ show ]

  def show
    flash[:notice] = "Parabéns #{current_user.name} por vencer a partida!!! Você recebeu 25 pontos no modo desafio. Veja sua posição no ranking #{helpers.link_to("aqui", match_challenge_scoreboards_path)}" if current_user == @match.winner
    flash[:notice] = "Poxa! Você perdeu a partida e, portanto, 25 pontos do modo desafio , mas não desanime #{current_user.name}, reveja seus erros e continue aprendendo!" if current_user == @match.loser
  end

  private

  def set_match
    @match = Match.find(params[:id])
  end

  def set_match_answers
    @player1_answers = fetch_player_answers(@match.player1)
    @player2_answers = fetch_player_answers(@match.player2)
    @player1_answer_count = fetch_correct_amount(@match.player1)
    @player2_answer_count = fetch_correct_amount(@match.player2)
  end

  def fetch_correct_amount(user)
    Answer.correct_answers.by_user(user).in_match(@match).valid.count
  end

  def fetch_player_answers(user)
    Answer.by_user(user).with_questions.in_match(@match)
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
  def match_status(status)
    statuses = {
      ongoing: "A partida está pronta para começar",
      awaiting: "Aguardando o jogador 2 entrar na partida",
      finished: "Partida encerrada"
    }
    statuses[status.to_sym]
    end
end

app/views/match/matches/_form.html.erb
<%= form_with(model: match, url: match_matches_url) do |form| %>
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
        <% match.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/match/matches/_lobby.html.erb
<% content_for :javascript do %>
  <%= javascript_pack_tag "matches" %>
<% end %>
<% content_for :page_title do %>
  Desafio - <%= "#{match.player1.name} versus #{ !match.player2.nil? ? match.player2.name : "..."}"%>
<% end %>

<div>
  <h4 id="status"> <%= match_status(@match.status) %></h4>
  <h2>Regras</h2>
  <ul>
    <li>Para jogar, o jogador deve possuir ao menos 25 pontos no modo desafio.</li>
    <li>O jogador deve responder 5 questões de temas sortidos.</li>
    <li>Há um limite de tempo sobre o qual a questão deve ser respondida para que seja contabilizada no resultado final.</li>
    <li>O jogador vencedor receberá 25 pontos de modo desafio, enquanto o perdedor perderá 25 pontos.</li>
    <li>É possível visualizar a sua posição no ranking de modo desafio em seu perfil.</li>
    <li>As resoluções e o resultado podem ser visualizadas na página de detalhes da partida, após concluir a resolução.</li>
  <ul>
  <% if @match.player1 != current_user && !@match.player2%>
    <%= link_to 'Deseja entrar na partida?', join_match_match_path(@match) , method: :put %>
  <% end %>
</div>

app/views/match/matches/_simple_form.html.erb
<%= form_with(model: match, url: match_matches_url) do |form| %>
  <%= form.submit "Novo desafio", class: "btn btn-primary text-end" %>
<% end %>

app/views/match/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/match/matches/index.html.erb
<% content_for :page_title do %>
  <div class="row">
    <div class="col-md-4">Minhas Partidas</div>
    <div class="col-md-4 offset-md-4 text-end"><%= render "match/matches/simple_form", match: @match %></div>
  </div>
<% end %>

<div class="card mb-4">
  <div class="card-header">
    <i class="fas fa-chart-area me-1"></i>
    Histórico de Partidas
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table">
        <thead>
            <tr>
                <th>Jogador 1</th>
                <th>Jogador 2</th>
                <th>Vencedor</th>
                <th>Status</th>
                <th>Detalhes</th>
            </tr>
        </thead>
        <tbody>
          <% @matches.each do |match| %>
            <tr>
              <td><%= match.player1.name %></td>
              <td><%= match.player2&.name %></td>
              <td><%= match.winner&.name %></td>
              <td><%= match_status(match.status) %></td>
              <% if match.finished? %>
                <td><%= link_to 'Ver detalhes', report_match_match_path(match) %></td>
              <% else %>
                <td><%= link_to 'Voltar a partida', match_match_path(match) %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
  <div class="card-footer small text-muted"></div>
</div>

app/views/match/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Back', match_matches_url %>

app/views/match/matches/question.html.erb
<% content_for :javascript do %>
  <%= javascript_pack_tag "matches" %>
<% end %>
<% content_for :page_title do %>
  Desafio <%= "#{@match.player1.name} versus #{@match.player2.name}" %>
<% end %>


<div class="card mb-4">
  <div class="card-header">
    <i class="fas fa-table me-1"></i>
    Questão
  </div>
  <div class="card-body">
    <%= render "questions/show", question: @question %>
    <%= render 'answers/form', answer: Answer.new(question_id: @question.id, match_id:  @match.id), url_opts: match_answers_path(@match.id), question: @question %>
  </div>
</div>

app/views/match/matches/report.html.erb
<div>
  <strong>Winner is</strong>
  <p><%= @match.winner %></p>
</div>

app/views/match/matches/show.html.erb
<div class="card mb-4">
  <div class="card-header">
    <i class="fas fa-chart-area me-1"></i>
    Desafio
  </div>
  <div class="card-body">
    <% if @match.awaiting? || @match.ongoing? %>
      <%= render 'match/matches/lobby', match: @match %>
      <% if (current_user == @match.player1 && !@match.player2.nil?) || current_user == @match.player2 %>
        <%= link_to 'Clique aqui para iniciar a partida', question_match_match_path(@match) %>
      <% end %>
    <% end %>
  </div>
  <div class="card-footer small text-muted"></div>
</div>
<%= link_to 'Back', match_match_path %>